
#define ASCDATA  64
#define BINDATA 128

#define OBJVAL (1 | BINDATA)
#define SRCVAL (2 | ASCDATA)
#define ASCVAL (4 | ASCDATA)
#define BINVAL (8 | BINDATA)
#define SIXBIT (16 | BINDATA)

#define ALLVAL (32 | BINDATA)

struct _file_type {
  char *ext;
  int types;
  char *desc;
};

#ifdef MAINDEFS

struct _file_type file_tab[] = {
  { "ABS", OBJVAL, "Absolute (nonrelocatable) program." },
  { "AID", SRCVAL, "Source file in AID language." },
  { "ALG", SRCVAL, "Source file in ALGOL language." },
  { "ALP", ASCVAL, "Printer forms alignment." },
  { "ATO", ASCVAL, "OPSER automatic command file." },
  { "AWT", BINVAL, "Data for automatic wire tester." },
  { "B10", SRCVAL, "Source file in BLISS-10." },
  { "B11", SRCVAL, "Source file in BLISS-11." },
  { "B16", ASCVAL, "Source file in BLISS-16." },
  { "B32", ASCVAL, "Source file in BLISS-32." },
  { "B36", ASCVAL, "Source file in BLISS-36." },
  { "BAC", OBJVAL, "Reserved for output from the BASIC compiler." },
  { "BAK", SRCVAL, "Backup file from TECO or SOS." },
  { "BAS", SRCVAL, "Source file in BASIC language." },
  { "BCM", ASCVAL, "Listing file created by FILCOM (binary compare)." },
  { "BCP", SRCVAL, "Source file in BCPL language." },
  { "BIN", BINVAL, "Binary file." },
  { "BLB", ASCVAL, "Blurb file." },
  { "BLI", SRCVAL, "Source file in BLISS language." },
  { "BUG", OBJVAL, "Saved to show a program error." },
  { "BWR", ASCVAL, "Beware file listing warnings about a file or program." },
  { "CAL", OBJVAL, "CAL data and program files." },
  { "CBL", SRCVAL, "Source file in COBOL language." },
  { "CCL", ASCVAL, "Alternate convention for command (@ command file construction for programs other than COMPIL)." },
  { "CCO", ASCVAL, "Listing of modifications to nonresident software." },
  { "CDP", ASCVAL|BINVAL, "Spooled output for card punch." },
  { "CFC", ASCVAL, "Compressed file compare. Group of .SCM files combined with PIP." },
  { "CKP", BINVAL, "Checkpoint core image file created by COBOL operating system." },
  { "CHN", OBJVAL, "CHAIN file." },
  { "CMD", ASCVAL, "Command file for indirect commands (@ construction for COMPIL)." },
  { "CMP", ASCVAL, "Complaint file by GRIPE." },
  { "COR", ASCVAL, "Correction file for SOUP." },
  { "CRF", ASCVAL, "CREF (cross-reference) input file." },
  { "CTL", ASCVAL, "Batch control file." },
  { "DAE", BINVAL, "Default output for DAEMON-taken core dumps." },
  { "DAT", ASCVAL|BINVAL, "Data (FORTRAN) file." },
  { "DBS", BINVAL, "Data Base Management System data file." },
  { "DDT", ASCVAL, "Input file to FILDDT." },
  { "DCT", ASCVAL, "Dictionary of words." },
  { "DIR", ASCVAL, "Directory from FILE command or DIRECT program." },
  { "DMP", ASCVAL, "COBOL compiler dump file." },
  { "DOC", ASCVAL, "Listing of modifications to the most recent version of the software." },
  { "DRW", BINVAL, "Drawing for VB10C drawing system." },
  { "DSE", ASCVAL, "Directory sorted by extension." },
  { "DSF", ASCVAL, "Directory sorted by file name." },
  { "ERR", ASCVAL, "Error message file." },
  { "EXE", OBJVAL, "Executable program." },
  { "F4 ",, "/ource Source file in Fortran-40 (FORTRAN) language." },
  { "FAI", SRCVAL, "Source file in FAIL language." },
  { "FFS", ASCVAL, "Fast FORTRAN stream." },
  { "FLO", ASCVAL, "English language flowchart." },
  { "FOR", SRCVAL, "Source file in FORTRAN-10 language." },
  { "FRM", ASCVAL, "Blank form for handwritten records." },
  { "FTP", SRCVAL, "FORTRAN test programs." },
  { "FUD", ASCVAL, "FUDGE2 listing output." },
  { "GND", ASCVAL, "List of ground pins for automatic wirewrap." },
  { "HGH", OBJVAL, "Nonsharable high segment of a high-segment program (created by SAVE command)." },
  { "HLP", ASCVAL, "Help files containing switch explanations, etc." },
  { "IDA", ASCVAL|BINVAL, "COBOL ISAM data file." },
  { "IDX", ASCVAL,, "SIXBIT Index file of a COBOL ISAM file." },
  { "INI", ASCVAL|BINVAL, "Initialization file." },
  { "LAP", ASCVAL, "Output from the LISP compiler." },
  { "LIB", ASCVAL, "COBOL source library." },
  { "LOG", ASCVAL, "MPB or LINK-10 log file." },
  { "LOW", OBJVAL, "Low segment of a two-segment program (created by SAVE command)." },
  { "LPT", ASCVAL, "Spooled output for line printer." },
  { "LSD", ASCVAL, "Default output for DUMP program." },
  { "LSQ", ASCVAL, "Queue listing created by QUEUE program." },
  { "LST", ASCVAL, "Listing data created by assemblers and compilers." },
  { "MAC", SRCVAL, "Source file in MACRO language." },
  { "MAN", ASCVAL, "Manual (documentation) file." },
  { "MAP", ASCVAL, "Loader or LINK-10 map file." },
  { "MEM", ASCVAL, "Memorandum file typically output from RUNOFF." },
  { "MIC", ASCVAL, "MIC command file." },
  { "MID", SRCVAL, "Source file in MIDAS (MIT Assembler) language" },
  { "MIM", BINVAL, "Snapshot of MIMIC simulator." },
  { "MSB", OBJVAL, "Music compiler binary output." },
  { "MUS", SRCVAL, "Music compiler input." },
  { "NEW", ALLVAL, "New version of a program or file." },
  { "OBJ", OBJVAL, "PDP-11 relocatable binary file." },
  { "OLD", SRCVAL,, "Object Backup source program." },
  { "OPR", ASCVAL, "Installation and assembly instructions." },
  { "OVR", OBJVAL, "COBOL overlay file." },
  { "P11", SRCVAL, "Source program in MACY11 language." },
  { "PAK", ASCVAL, "Files compressed by PACK.TEC to save disk space." },
  { "PAL", SRCVAL, "Source file in PAL10 (PDP-8 assembler)." },
  { "PAS", SRCVAL, "Source file in Pascal language." },
  { "PL1", SRCVAL, "Source file in PL1 language." },
  { "PLM", ASCVAL, "Program Logic Manual." },
  { "PLO", BINVAL, "Compressed plot output." },
  { "PLT", ASCVAL, "Spooled output for plotter." },
  { "PPL", SRCVAL, "Source file in PPL language." },
  { "PTP", ASCVAL|BINVAL, "Spooled output for paper-tape punch." },
  { "Q??", ASCVAL, "Edit backup file, like .BAK (all xx)." },
  { "QUD", ASCVAL|BINVAL, "Queued data file." },
  { "QUE", BINVAL, "Queue request file." },
  { "QUF", BINVAL, "Master queue and request file." },
  { "REL", OBJVAL, "Relocatable binary file." },
  { "RIM", OBJVAL, "RIM loader file." },
  { "RMT", OBJVAL, "Read-in mode (RIM) format file (PIP)." },
  { "RNB", ASCVAL, "RUNOFF input for producting a .BLB file." },
  { "RNC", ASCVAL, "RUNOFF input for producing a .CCO file." },
  { "RND", ASCVAL, "RUNOFF input for producing a .DOC file." },
  { "RNE", ASCVAL, "RUNOFF input for error message text." },
  { "RNH", ASCVAL, "RUNOFF input for producing a .HLP file." },
  { "RNL", ASCVAL, "RUNOFF input for program logic manual." },
  { "RNM", ASCVAL, "RUNOFF input for producing a .MAN file." },
  { "RNO", ASCVAL, "Programming specifications in RUNOFF input to produce .MEM file." },
  { "RNP", ASCVAL, "RUNOFF input for producing a .OPR file." },
  { "RNS", ASCVAL, "RUNOFF input for text file of standards." },
  { "RSP", ASCVAL, "Script response time log file." },
  { "RSX", ALLVAL, "Files for RSX-11D." },
  { "RTB", OBJVAL, "Read-in mode (RIM10B) format file (PIP)." },
  { "SAI", SRCVAL, "Source file in SAIL language." },
  { "SCD", ASCVAL, "Differences in directory." },
  { "SCM", ASCVAL, "Listing file created by FILCOM (source compare)." },
  { "SCP", ASCVAL, "SCRIPT control file." },
  { "SEQ", ASCVAL|SIXBIT, "Sequential COBOL data file, input to ISAM program." },
  { "SFD", BINVAL, "Subfile directory (reserved usage)." },
  { "SIM", SRCVAL, "Source file in SIMULA language." },
  { "SMP", SRCVAL, "Source file in SIMPLE language." },
  { "SNO", SRCVAL, "Source file in SNOBOL language." },
  { "SNP", ASCVAL, "Snapshot of disk by DSKLST." },
  { "SOS", ASCVAL, "SOS command file." },
  { "SPC", ASCVAL, "Corrected file for SPELL program." },
  { "SPD", ASCVAL, "Dictionary for SPELL program." },
  { "SPM", ASCVAL, "File of misspelled words for SPELL program." },
  { "SPU", ASCVAL, "File of upper case words for SPELL program." },
  { "SPX", ASCVAL, "File of exception (error) lines for SPELL program." },
  { "SRC", ASCVAL, "Source files." },
  { "STD", ASCVAL, "Standards." },
  { "SVE", OBJVAL, ".SAVed file from a single user monitor." },
  { "SYM", BINVAL, "LINK-10 symbol file." },
  { "SYS", BINVAL, "Special system files." },
  { "TEC", ASCVAL, "TECO macro." },
  { "TEM", ASCVAL|BINVAL, "Temporary files." },
  { "TMP", ASCVAL|BINVAL, "Temporary files." },
  { "TPB", ASCVAL, "Typeset input for producing a .BLB file." },
  { "TPC", ASCVAL, "Typeset input for producing a .CCO file." },
  { "TPD", ASCVAL, "Typeset input for producing a .DOC file." },
  { "TPE", ASCVAL, "Typeset input for producing error message text." },
  { "TPH", ASCVAL, "Typeset input for producing a .HLP file." },
  { "TPL", ASCVAL, "Typeset input for producing a logic manual." },
  { "TPM", ASCVAL, "Typeset for producing a .MAN file." },
  { "TPO", ASCVAL, "Typeset input for producing a programming specification." },
  { "TPP", ASCVAL, "Typeset input for producing an .OPR file." },
  { "TST", ALLVAL, "Test data." },
  { "TXT", ASCVAL, "Text file." },
  { "UFD", BINVAL, "User file directory (reserved usage)." },
  { "UPD", ASCVAL, "Updates flagged in margin (FILCOM)." },
  { "VMX", OBJVAL, "Expanded save file starting at a location greater than zero and used as a special support program for virtual memory." },
  { "WCH", ASCVAL, "SCRIPT monitor (WATCH) file." },
  { "WRL", ASCVAL, "Wirelist." },
  { "XOR", BINVAL, "Module data for XOR tester." },
  { "XPN", OBJVAL, "Expanded save file (FILEX and LINK-10)." },
  { "Z??", ASCVAL, "Edit original file (all xx)." },
  { NULL, 0, NULL}
};

#else

extern struct _file_type file_tab[];

#endif
